### ISSUE TITLE
Updated login.ejs

### ISSUE THREAD

**Issue by aishanaaz19** [anirudh12032008/codehealers#1]
`<%- include("components/header.ejs") %>
<style>
    * {
    font-family: 'Poppins', sans-serif;
}

.container {
    position: relative;
    width: 70vw;
    height: 80vh;
    background: #fff;
    border-radius: 15px;
    box-shadow: 0 4px 20px 0 rgba(0, 0, 0, 0.3), 0 6px 20px 0 rgba(0, 0, 0, 0.3);
    overflow: hidden;
}
.container::before {
    content: "";
    position: absolute;
    top: 0;
    left: -50%;
    width: 100%;
    height: 100%;
    background-color: #0D9276;
    z-index: 6;
    transform: translateX(100%);
    transition: 1s ease-in-out;
}
.signin-signup {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: space-around;
    z-index: 5;
}
form {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
    width: 40%;
    min-width: 238px;
    padding: 0 10px;
}
form.sign-in-form {
    opacity: 1;
    transition: 0.5s ease-in-out;
    transition-delay: 1s;
}
form.sign-up-form {
    opacity: 0;
    transition: 0.5s ease-in-out;
    transition-delay: 1s;
}
.title {
    font-size: 2rem;
    color: #0D9276;
    margin-bottom: 3rem;
}
.input-field {
    width: 100%;
    height: 3rem;
    background: #fff;
    margin: 0.75rem;
    border-bottom: 1px solid #666;
    display: flex;
    align-items: center;
}
.input-field i {
    flex: 1;
    text-align: center;
    color: #666;
    font-size: 1rem;
}
.input-field input {
    flex: 5;
    background: none;
    border: none;
    outline: none;
    width: 100%;
    font-size: 1rem;
    font-weight: 500;
    color: #666;
}
.btn {
    width: 30%;
    height: auto;
    border: 1px solid #0D9276;
    border-radius: .6rem;
    background: #0D9276;
    color: #fff;
    font-weight: 500;
    margin: 2rem 0;
    padding: 10px;
    font-size: .8rem;
    text-transform: uppercase;
    cursor: pointer;
}
.btn:hover {
    background: #fff;
    color: #0D9276;
}
#sign-up-btn{
    border: 1px solid #fff;
}
#sign-in-btn{
    border: 1px solid #fff;
}
a {
    text-decoration: none;
}
.panels-container {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    align-items: center;
    justify-content: space-around;
}
.panel {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-around;
    width: 35%;
    min-width: 238px;
    padding: 0 10px;
    text-align: center;
    z-index: 6;
}
.left-panel {
    pointer-events: none;
}
.content {
    color: #fff;
    transition: 1.1s ease-in-out;
    transition-delay: 0.5s;
}
.panel h3 {
    font-size: 24px;
    font-weight: 600;
}
.panel p {
    font-size: 15px;
    padding: 10px 0;
}
.image {
    width: 100%;
    transition: 1.1s ease-in-out;
    transition-delay: 0.4s;
}
.left-panel .image,
.left-panel .content {
    transform: translateX(-200%);
}
.right-panel .image,
.right-panel .content {
    transform: translateX(0);
}
.account-text {
    display: none;
}
/*Animation*/
.container.sign-up-mode::before {
    transform: translateX(0);
}
.container.sign-up-mode .right-panel .image,
.container.sign-up-mode .right-panel .content {
    transform: translateX(200%);
}
.container.sign-up-mode .left-panel .image,
.container.sign-up-mode .left-panel .content {
    transform: translateX(0);
}
.container.sign-up-mode form.sign-in-form {
    opacity: 0;
}
.container.sign-up-mode form.sign-up-form {
    opacity: 1;
}
.container.sign-up-mode .right-panel {
    pointer-events: none;
}
.container.sign-up-mode .left-panel {
    pointer-events: all;
}
/*Responsive*/
@media (max-width:779px) {
    .container {
        width: 100vw;
        height: 100vh;
    }
}
@media (max-width:635px) {
    .container::before {
        display: none;
    }
    form {
        width: 80%;
    }
    form.sign-up-form {
        display: none;
    }
    .container.sign-up-mode2 form.sign-up-form {
        display: flex;
        opacity: 1;
    }
    .container.sign-up-mode2 form.sign-in-form {
        display: none;
    }
    .panels-container {
        display: none;
    }
    .account-text {
        display: initial;
        margin-top: 30px;
    }
}
@media (max-width:320px) {
    form {
        width: 90%;
    }
}
</style>
<div class="bg-[#CBE4DE] flex items-center justify-center min-h-screen">
    <div class="container">
        <div class="signin-signup ">
            <form action="/login" class="sign-in-form" method="get">
                <h2 class="title">Sign in</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" placeholder="Username">
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" placeholder="Password">
                </div>
                <input type="submit" value="Login" class="btn">
                <p class="account-text">Don't have an account? <a href="#" id="sign-up-btn2">Sign up</a></p>
            </form>
            <form action="" class="sign-up-form">
                <h2 class="title">Sign up</h2>
                <div class="input-field">
                    <i class="fas fa-user"></i>
                    <input type="text" placeholder="Username">
                </div>
                <div class="input-field">
                    <i class="fas fa-envelope"></i>
                    <input type="text" placeholder="Email">
                </div>
                <div class="input-field">
                    <i class="fas fa-lock"></i>
                    <input type="password" placeholder="Password">
                </div>
                <input type="submit" value="Sign up" class="btn">
                <p class="account-text">Already have an account? <a href="#" id="sign-in-btn2">Sign in</a></p>
            </form>
        </div>
        <div class="panels-container">
            <div class="panel left-panel">
                <div class="content">
                    <h3>Member of Health Buddy?</h3>
                    <p>Log In to get back in your account.</p>
                    <button class="btn " id="sign-in-btn">Sign in</button>
                </div>
            </div>
            <div class="panel right-panel">
                <div class="content">
                    <h3>New to Health Buddy?</h3>
                    <p>Register Now! To get instance service on your emergency.</p>
                    <button class="btn" id="sign-up-btn">Sign up</button>
                </div>
            </div>
        </div>
    </div>
</div>    
        
    
    <script>
        const sign_in_btn = document.querySelector("#sign-in-btn");
        const sign_up_btn = document.querySelector("#sign-up-btn");
        const container = document.querySelector(".container");
        const sign_in_btn2 = document.querySelector("#sign-in-btn2");
        const sign_up_btn2 = document.querySelector("#sign-up-btn2");
        sign_up_btn.addEventListener("click", () => {
        container.classList.add("sign-up-mode");
        });
        sign_in_btn.addEventListener("click", () => {
        container.classList.remove("sign-up-mode");
        });
        sign_up_btn2.addEventListener("click", () => {
        container.classList.add("sign-up-mode2");
        });
        sign_in_btn2.addEventListener("click", () => {
        container.classList.remove("sign-up-mode2");
        });
    </script>

`

**Comment by anirudh12032008** [comment]
@aishanaaz19 what you have done?
