### ISSUE TITLE
OpenAi API key required for the project to run

### ISSUE THREAD

**Issue by aaditya-paul** [anirudh12032008/codehealers#10]
![image](https://github.com/anirudh12032008/codehealers/assets/91450480/b9f38d2b-30c8-4c43-81a7-135ccfaf99f8)

**Comment by anirudh12032008** [comment]
> ![image](https://github.com/anirudh12032008/codehealers/assets/91450480/b9f38d2b-30c8-4c43-81a7-135ccfaf99f8)
> 

You need to insert your own API keys in a `.env` file if you are trying to setup the project locally.

**Comment by aaditya-paul** [comment]
> > ![image](https://github.com/anirudh12032008/codehealers/assets/91450480/b9f38d2b-30c8-4c43-81a7-135ccfaf99f8)
> > 
> 
> You need to insert your own API keys in a `.env` file if you are trying to setup the project locally. 

Okay, thanks for the help !
